name: CI Ruby

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Ruby
      uses: actions/setup-ruby@latest
      with:
        ruby-version: 3.2.2

    - name: Instalar dependências
      run: |
        gem install bundler
        bundle install

    - name: Executar testes
      run: |
        bundle exec cucumber -t @regression